import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "./auth/Providers";
import SideBar from "@/components/SideBar";
import CheckRoute from "@/components/CheckRoute";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/authOptions";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Taskify",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  return (
    <html data-theme="halloween" lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <main className="p-5 flex gap-2">
            <CheckRoute />
            {children}
          </main>
        </AuthProvider>
      </body>
    </html>
  );
}
